[tool.poetry]
name = "media-service"
version = "0.1.0"
description = "SignRoad Media Service"
authors = ["SignRoad Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.122.0"
uvicorn = "^0.38.0"
python-jose = "^3.5.0"
passlib = "^1.7.4"
bcrypt = "^5.0.0"
python-multipart = "^0.0.20"
sqlalchemy = "^2.0.44"
alembic = "^1.17.2"
asyncpg = "^0.31.0"
psycopg2-binary = "^2.9.11"
email-validator = "^2.3.0"
slowapi = "^0.1.9"
structlog = "^25.5.0"
redis = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
